### ISSUE TITLE
Importação de OFX não funciona

### ISSUE THREAD

**Issue by FelipeR2U** [ciceromsjr/myfinancesplugin#38]
```stack
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:6)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NumberFormatException: For input string: "xxxx,xx"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at cicero.minhasfinancas.util.ofx.OFX.g(OFX.java:5)
	at cicero.minhasfinancas.util.ofx.OFXParser.a(OFXParser.java:13)
	at cicero.minhasfinancas.util.ofx.OFXImport.a(OFXImport.java:3)
	at cicero.minhasfinancas.loaders.TransacoesOFXLoader.M(TransacoesOFXLoader.java:1)
	at cicero.minhasfinancas.loaders.TransacoesOFXLoader.H(TransacoesOFXLoader.java:1)
	at androidx.loader.content.AsyncTaskLoader.J(AsyncTaskLoader.java:1)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.n(AsyncTaskLoader.java:1)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.b(AsyncTaskLoader.java:1)
	at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:3)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```
Modifiquei a string, mas de qualquer forma parece que o erro está em esperar um valor de ponto decimal enquanto os OFX do Brasil são gerados com vírgula.

**Comment by FelipeR2U** [comment]
@ciceromsjr , poderia sugerir um PR no repo do app, mas este é fechado. Você poderia corrigir isso? Paguei as features premium quase que apenas por esse tipo de importação...

**Comment by FelipeR2U** [comment]
Abrindo o OFX vejo que está com ponto decimal mesmo. Estranho esta conversão que foi feita, acho que o APP está realmente causando o erro de formatos
